# First stage: Generate Nuxt app
FROM loeken/enso-template-base-dev:3.18 as base


# Install necessary tools and dependencies
RUN sudo apk add --no-cache go

COPY . .

# install gopls for development
RUN go install -v golang.org/x/tools/gopls@latest

CMD ["go", "run", "main.go"]
#CMD ["tail", "-f", "/dev/null"]
