# First stage: Generate Nuxt app
FROM golang:1.20.6-alpine3.18

# Install necessary tools and dependencies
RUN apk add --no-cache git curl bash gpg sudo openssh zsh apk-tools-zsh-completion nodejs npm

# Set the argument for user id and group id
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN mkdir -p /app

# Create a new group using the provided group id and create a new user 'vscode' with the provided user id in that group
RUN addgroup -g $GROUP_ID vscode \
    && adduser -D -u ${USER_ID} -G vscode vscode \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode \
    && chmod 0440 /etc/sudoers.d/vscode \
    && chown -R vscode:vscode /app

# switch to non root user
USER vscode
WORKDIR /app

SHELL ["/bin/zsh", "-c"]
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

## app specific


COPY . .

# install gopls for development / dlv for debug
RUN go install -v golang.org/x/tools/gopls@latest 
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

RUN sudo chown -R vscode:vscode /app
RUN git config --global --add safe.directory /app
# CMD ["go", "run", "main.go"]
CMD ["tail", "-f", "/dev/null"]
