# First stage: Generate Nuxt app
FROM enso-template-base-dev:3.18

# Set the argument for user id and group id
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN mkdir -p /app
# Create a new group using the provided group id and create a new user 'vscode' with the provided user id in that group
RUN addgroup -g $GROUP_ID vscode \
    && adduser -D -u ${USER_ID} -G vscode vscode \
    && chown -R vscode:vscode /app

# switch to non root user
USER vscode
WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
