annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: inital release
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.10.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 13.1.1
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.0
description: myapp
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: myapp
type: application
version: 1.0.0
