# -- global name of this application
global:
  fullnameOverride: myapp

# -- the controller is your main application running
controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: traefik/whoami
          tag: v1.10
          pullPolicy: IfNotPresent

        # -- environment variables.
        env:
          TZ: UTC

# -- configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http

# -- configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: false
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config

# -- load databases as subcharts, the values for these charts can be used within these blocks directly
postgresql:
  enabled: false

mariadb:
  enabled: false

redis:
  enabled: false


