name: Build and Push Docker image to GCR

on: 
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: myapp
  GCP_PROJECT_ID: projectid-1337
  GCR_HOSTNAME: europe-west3-docker.pkg.dev
  DOCKERFILE_PATH: ./deploy/docker/Dockerfile.prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.GCR_HOSTNAME }}
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/enso/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        build-args: BUILD_VERSION=${{ github.ref_name }}